#requires -Version 7.0
[CmdletBinding()]
param(
  [ValidateSet('Install','Uninstall')][string]$Action = 'Install',
  [string]$Repository = '.',
  [string]$Executable = (Join-Path (Split-Path $PSScriptRoot) '_build/native/debug/build/cmd/nbinspect/nbinspect.exe'),
  [string]$Config = '',
  [ValidateSet('','error','warning','info')][string]$FailOn = ''
)
$ErrorActionPreference = 'Stop'
$utf8 = [Text.UTF8Encoding]::new($false, $true)

function Invoke-Git([string[]]$Arguments) {
  $psi = [Diagnostics.ProcessStartInfo]::new('git')
  $psi.WorkingDirectory = $script:repositoryDirectory
  $psi.UseShellExecute = $false
  $psi.RedirectStandardOutput = $true; $psi.RedirectStandardError = $true
  $psi.StandardOutputEncoding = $utf8; $psi.StandardErrorEncoding = $utf8
  foreach ($argument in $Arguments) { [void]$psi.ArgumentList.Add($argument) }
  $process = [Diagnostics.Process]::new(); $process.StartInfo = $psi
  try {
    [void]$process.Start()
    $stdout = $process.StandardOutput.ReadToEndAsync()
    $stderr = $process.StandardError.ReadToEndAsync()
    if (!$process.WaitForExit(30000)) { $process.Kill($true); throw 'Git query timed out' }
    return @{code=$process.ExitCode; output=$stdout.GetAwaiter().GetResult().TrimEnd("`r","`n"); error=$stderr.GetAwaiter().GetResult()}
  } finally { $process.Dispose() }
}
function Git-Value([string[]]$Arguments) {
  $result = Invoke-Git $Arguments
  if ($result.code -ne 0) { throw "Git query failed: $($result.error.Trim())" }
  return $result.output
}
function Quote-Sh([string]$Value) {
  if ($Value -match '[\x00-\x1f\x7f]' -or $Value.Length -gt 4096) { throw 'Hook path contains control characters or exceeds 4096 characters' }
  $escape = "'" + [char]34 + "'" + [char]34 + "'"
  return "'" + $Value.Replace('\','/').Replace("'",$escape) + "'"
}
function Resolve-File([string]$Value,[string]$BaseDirectory) {
  $absolute = if ([IO.Path]::IsPathRooted($Value)) { $Value } else { Join-Path $BaseDirectory $Value }
  $item = Get-Item -LiteralPath $absolute -Force
  if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw "Expected an ordinary file: $absolute" }
  return $item.FullName
}
function Digest([string]$Body) {
  return [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($utf8.GetBytes($Body))).ToLowerInvariant()
}
function Read-ManagedHook([string]$Path) {
  $item = Get-Item -LiteralPath $Path -Force
  if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -or $item.Length -gt 131072) { throw 'Existing pre-commit is not an ordinary NBInspect hook; left unchanged' }
  $content = $utf8.GetString([IO.File]::ReadAllBytes($Path))
  $match = [regex]::Match($content,'\A#!/bin/sh\n# NBInspect pre-commit v1 sha256:([0-9a-f]{64})\n(.*)\z',[Text.RegularExpressions.RegexOptions]::Singleline)
  if (!$match.Success -or !$match.Groups[2].Value.StartsWith("# Generated by NBInspect; reinstall to change settings.`n") -or (Digest $match.Groups[2].Value) -cne $match.Groups[1].Value) {
    throw 'Existing pre-commit is foreign or modified; left unchanged'
  }
  return $content
}

try {
  if (!$IsWindows) { throw 'Hook management currently requires Windows and PowerShell 7' }
  foreach ($name in @('GIT_DIR','GIT_WORK_TREE','GIT_COMMON_DIR','GIT_INDEX_FILE')) {
    if ([Environment]::GetEnvironmentVariable($name)) { throw "Unset $name before managing hooks; Git repository overrides are not supported" }
  }
  $script:repositoryDirectory = (Get-Item -LiteralPath $Repository -Force).FullName
  $script:repositoryDirectory = Git-Value @('rev-parse','--show-toplevel')
  $hooksConfig = Invoke-Git @('config','--get','core.hooksPath')
  if ($hooksConfig.code -eq 0) { throw 'core.hooksPath is configured; manage your existing hook system manually (configuration left unchanged)' }
  if ($hooksConfig.code -ne 1) { throw 'Cannot read core.hooksPath configuration' }
  $common = [IO.Path]::GetFullPath((Git-Value @('rev-parse','--path-format=absolute','--git-common-dir')))
  $hooks = [IO.Path]::GetFullPath((Git-Value @('rev-parse','--path-format=absolute','--git-path','hooks')))
  if (![string]::Equals($hooks,(Join-Path $common 'hooks'),[StringComparison]::OrdinalIgnoreCase)) { throw 'Unexpected hooks directory; refusing to modify it' }
  # Refuse junctions/symlinks between the common Git directory and its hooks.
  foreach ($directory in @($common,$hooks)) {
    if (Test-Path -LiteralPath $directory) {
      $item = Get-Item -LiteralPath $directory -Force
      if (!$item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Git hooks directory is a link or not a directory; left unchanged' }
    }
  }
  $hook = Join-Path $hooks 'pre-commit'
  if ($Action -eq 'Uninstall') {
    if ($PSBoundParameters.ContainsKey('Executable') -or $Config -or $FailOn) { throw 'Uninstall accepts only Repository and Action' }
    if (!(Test-Path -LiteralPath $hook)) { Write-Output 'NBInspect pre-commit is not installed'; exit 0 }
    [void](Read-ManagedHook $hook)
    [IO.File]::Delete($hook)
    Write-Output "Removed NBInspect pre-commit: $hook"
    exit 0
  }
  $binary = Resolve-File $Executable (Get-Location).Path
  $argv = @((Quote-Sh $binary),'review-git','--staged','--format','text')
  if ($Config) { $argv += @('--config',(Quote-Sh (Resolve-File $Config $script:repositoryDirectory))) }
  if ($FailOn) { $argv += @('--fail-on',$FailOn) }
  # Preserve Git's environment, including a temporary GIT_INDEX_FILE for commit --only.
  $body = "# Generated by NBInspect; reinstall to change settings.`nexec " + ($argv -join ' ') + "`n"
  $content = "#!/bin/sh`n# NBInspect pre-commit v1 sha256:" + (Digest $body) + "`n" + $body
  if (Test-Path -LiteralPath $hook) {
    $existing = Read-ManagedHook $hook
    if ($existing -cne $content) { throw 'NBInspect hook has different settings; uninstall it before reinstalling' }
    Write-Output "NBInspect pre-commit already installed: $hook"
    exit 0
  }
  [void][IO.Directory]::CreateDirectory($hooks)
  # CreateNew also refuses a hook created by another process after the check.
  $file = [IO.FileStream]::new($hook,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None)
  try { $bytes = $utf8.GetBytes($content); $file.Write($bytes,0,$bytes.Length) }
  finally { $file.Dispose() }
  Write-Output "Installed NBInspect pre-commit: $hook"
  Write-Output 'This Git hooks directory is shared by linked worktrees. Nonzero review exits block commits.'
} catch {
  [Console]::Error.WriteLine("NBInspect hook: $($_.Exception.Message)")
  exit 2
}
